# Простой рабочий процесс для развертывания статического контента на GitHub Pages
name: Deploy static content to Pages

on:
  # Запускается при пушах в основную ветку
  push:
    branches: ['master']

  # Позволяет запускать этот рабочий процесс вручную из вкладки Actions
  workflow_dispatch:

# Устанавливает разрешения для GITHUB_TOKEN для развертывания на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Разрешает одновременное развертывание
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Один задание для развертывания
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Yarn
        run: npm install -g yarn
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Загрузка папки dist
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
